name: Release mosdns

on:
  workflow_dispatch:

jobs:

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: |
          wget -qO${{ github.workspace }}/mosdns.zip https://api.github.com/repos/IrineSistiana/mosdns/zipball/$(wget -qO- -e https-proxy=127.0.0.1:12604 https://api.github.com/repos/IrineSistiana/mosdns/releases/latest | grep tag_name | awk '{print $2}' | sed 's/[",]//g')
          unzip ${{ github.workspace }}/mosdns.zip -d ${{ github.workspace }}/mosdns
          cp -rf ./mosdns/$(ls ./mosdns)/* ./mosdns
          cd ${{ github.workspace }}/mosdns
          go test -race -v ./...

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build
        run: |
          cd ${{ github.workspace }}/mosdns
          python ./release.py
        env:
          CGO_ENABLED: '0'
      - name: Generate release tag
        id: tag
        if: (!cancelled())
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
          [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
          echo "::set-output name=status::success"
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          files: '${{ github.workspace }}/mosdns/release/mosdns*.zip'
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
